# Day 4 – NumPy Fundamentals & Student Marks Analysis

**Intern:** Shri Sanjaykumar V  
**Role:** AI/ML Intern  
**Date:** 01 September 2026  

This notebook covers foundational array concepts using **NumPy** (Numerical Python) and demonstrates a practical **Student Marks Analysis**.

## 1. Introduction to NumPy

NumPy stands for **Numerical Python**. It is the core library for scientific and numerical computing in Python.

### Why NumPy is Essential in AI/ML:
- **Multi-dimensional Arrays:** Provides the `ndarray` object representing vectors (1D) and matrices (2D/3D).
- **Vectorized Operations:** Performs arithmetic and mathematical operations without slow Python `for` loops.
- **Memory Efficiency:** Stores data in contiguous memory blocks, making computations much faster.
- **Foundation of AI/ML:** Libraries like Pandas, Scikit-learn, TensorFlow, and PyTorch are built on top of NumPy arrays.

## 2. Importing NumPy & Version Check

In [1]:
import numpy as np

print("NumPy successfully imported. Version:", np.__version__)

NumPy successfully imported. Version: 2.5.0


## 3. Creating a 1D Array
A 1D array represents a single vector of numbers.

In [2]:
# Create 1D array from a Python list
arr_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr_1d)
print("Shape:", arr_1d.shape)
print("Dimensions:", arr_1d.ndim)
print("Data Type:", arr_1d.dtype)

1D Array: [10 20 30 40 50]
Shape: (5,)
Dimensions: 1
Data Type: int32


## 4. Creating a 2D Array
A 2D array represents a grid or table of rows and columns (matrix).

In [3]:
# Create a 2D array (matrix)
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("2D Array:\n", arr_2d)
print("Shape:", arr_2d.shape, "(2 rows, 3 columns)")
print("Dimensions:", arr_2d.ndim)
print("Total Elements:", arr_2d.size)

2D Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3) (2 rows, 3 columns)
Dimensions: 2
Total Elements: 6


## 5. Indexing in Arrays
Accessing individual elements using 0-based index positions.

In [4]:
# 1D array indexing
print("First element of 1D array:", arr_1d[0])
print("Last element of 1D array:", arr_1d[-1])

# 2D array indexing [row, column]
print("Element at Row 0, Column 1 in 2D array:", arr_2d[0, 1])
print("Element at Row 1, Column 2 in 2D array:", arr_2d[1, 2])

First element of 1D array: 10
Last element of 1D array: 50
Element at Row 0, Column 1 in 2D array: 20
Element at Row 1, Column 2 in 2D array: 60


## 6. Slicing in Arrays
Extracting sub-arrays using `[start:stop:step]` syntax.

In [5]:
# 1D slicing
print("1D slice (index 1 to 3):", arr_1d[1:4])
print("1D slice (first 3 elements):", arr_1d[:3])

# 2D slicing [row_slice, col_slice]
print("2D slice (first row):", arr_2d[0, :])
print("2D slice (all rows, column 1 to end):\n", arr_2d[:, 1:])

1D slice (index 1 to 3): [20 30 40]
1D slice (first 3 elements): [10 20 30]
2D slice (first row): [10 20 30]
2D slice (all rows, column 1 to end):
[[20 30]
 [50 60]]


## 7. Basic Mathematical Operations
Using built-in statistical and mathematical functions.

In [6]:
numbers = np.array([10, 25, 40, 55, 70])

print("Numbers:", numbers)
print("Sum    :", np.sum(numbers))
print("Mean   :", np.mean(numbers))
print("Max    :", np.max(numbers))
print("Min    :", np.min(numbers))

# Element-wise arithmetic
print("Add 5 to all elements:", numbers + 5)
print("Multiply all by 2    :", numbers * 2)

Numbers: [10 25 40 55 70]
Sum    : 200
Mean   : 40.0
Max    : 70
Min    : 10
Add 5 to all elements: [15 30 45 60 75]
Multiply all by 2    : [ 20  50  80 110 140]


## 8. Python List vs. NumPy Array Comparison

| Feature | Python List | NumPy Array |
| :--- | :--- | :--- |
| **Data Types** | Heterogeneous (can mix strings, ints, objects) | Homogeneous (single numeric data type) |
| **Memory** | Non-contiguous memory allocation | Contiguous memory allocation (compact) |
| **Arithmetic** | Concatenates or repeats (`+`, `*`) | Element-wise vectorized calculation |
| **Performance** | Slower for large numerical calculations | Optimized in C, highly efficient for AI/ML |

In [7]:
# Demonstration of '+' behavior
py_list = [1, 2, 3]
np_arr = np.array([1, 2, 3])

print("List '+' operation (concatenation):", py_list + py_list)
print("NumPy '+' operation (element-wise):", np_arr + np_arr)

List '+' operation (concatenation): [1, 2, 3, 1, 2, 3]
NumPy '+' operation (element-wise): [2 4 6]


## 9. Student Marks Analysis Using NumPy

Here we analyze a dataset of marks for **4 students** across **3 subjects** (Subject 1, Subject 2, Subject 3) using basic NumPy operations.

In [8]:
# 2D array: Rows = Students (1 to 4), Columns = Subjects (1 to 3)
marks = np.array([
    [85, 78, 90],  # Student 1
    [92, 88, 95],  # Student 2
    [70, 65, 80],  # Student 3
    [88, 82, 84]   # Student 4
])

print("Student Marks Matrix (Rows = Students, Cols = Subjects):\n", marks)

# 1. Overall Statistics
print("\n--- Overall Class Metrics ---")
print("Total Marks Scored across all:", np.sum(marks))
print(f"Overall Class Average        : {np.mean(marks):.2f}")
print("Highest Score in Class       :", np.max(marks))
print("Lowest Score in Class        :", np.min(marks))

# 2. Per-Student Metrics (sum across columns, axis=1)
student_totals = np.sum(marks, axis=1)
student_averages = np.mean(marks, axis=1)

print("\n--- Per-Student Performance ---")
for i in range(len(student_totals)):
    print(f"Student {i+1}: Total = {student_totals[i]}, Average = {student_averages[i]:.2f}")

# 3. Per-Subject Average (mean down rows, axis=0)
subject_averages = np.mean(marks, axis=0)
print("\n--- Per-Subject Averages ---")
for j in range(len(subject_averages)):
    print(f"Subject {j+1} Average: {subject_averages[j]:.2f}")

Student Marks Matrix (Rows = Students, Cols = Subjects):
[[85 78 90]
 [92 88 95]
 [70 65 80]
 [88 82 84]]
Total Marks Scored across all: 997
Overall Class Average        : 83.08
Total Marks Scored across all: 1009
Overall Class Average        : 84.08
Highest Score in Class       : 95
Lowest Score in Class        : 65

--- Per-Student Performance ---
Student 1: Total = 253, Average = 84.33
Student 2: Total = 275, Average = 91.67
Student 3: Total = 215, Average = 71.67
Student 4: Total = 254, Average = 84.67

--- Per-Subject Averages ---
Subject 1 Average: 83.75
Subject 2 Average: 78.25
Subject 3 Average: 87.25


## 10. Conclusion

In Day 4:
- Learned to create and inspect 1D and 2D NumPy arrays.
- Practiced array indexing and slicing to extract subsets of data.
- Applied built-in mathematical functions (`sum`, `mean`, `max`, `min`) across whole arrays and specific axes.
- Understood why NumPy arrays are preferred over standard Python lists for data analysis and AI/ML workflows.
- Successfully completed a Student Marks Analysis calculating class, student, and subject statistics.